paths:
  originals: "work/to_process"
  cleaned_input: "inputs/_originals"
  cleaned_output: "work/cleaned"
  work: "work"
  wiki: "wiki"
  tmp: "work/tmp"

options:
  ocr: false
  cutoff_similarity: 0.5
